#!/usr/bin/with-contenv bash
#shellcheck shell=bash disable=SC2153,SC2164,SC2016

# -----------------------------------------------------------------------------------
# Copyright 2022 kx1t - licensed under the terms and conditions
# of the MIT License. The terms and conditions of this license are included with the Github
# distribution of this package, and are also available here:
# https://github.com/kx1t/docker-skysquitter/

# redirect stderr to stdout so it's picked up in the docker logs
exec 2>&1
# all errors will show a line number and the command used to produce the error
SCRIPT_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd)/$(basename "$0")"
trap 'echo -e "[ERROR] $SCRIPT_PATH in line $LINENO when executing: $BASH_COMMAND"' ERR

APPNAME="$(hostname)/ssq-feeder"

if [[ -f /run/recv_host_ip ]]
then
  RECV_HOST="$(cat /run/recv_host_ip)"
fi

SET_TIMESTAMP="${SET_TIMESTAMP,,}"
if [[ "$SET_TIMESTAMP" == "true" ]] || [[ "$SET_TIMESTAMP" == "on" ]] || [[ "$SET_TIMESTAMP" == "enabled" ]]
then
    SET_TIMESTAMP="TRUE"
else
    SET_TIMESTAMP=""
fi

BEAST_FEEDER_COMMAND=()
BEAST_FEEDER_COMMAND+=("/usr/local/bin/beast-feeder")
BEAST_FEEDER_COMMAND+=("${RECV_HOST}")
BEAST_FEEDER_COMMAND+=("${RECV_PORT}")
BEAST_FEEDER_COMMAND+=("${DEST_HOST}")
BEAST_FEEDER_COMMAND+=("${DEST_PORT}")
BEAST_FEEDER_COMMAND+=("${SET_TIMESTAMP}")

echo "[$(date)][$APPNAME] Started as an s6 service"
echo "[$(date)][$APPNAME] SkySquitter Container Version: $(cat /.VERSION.docker-skysquitter)"
echo "[$(date)][$APPNAME] Beast-Feeder Version: $(cat /.VERSION.beast-feeder)"
echo "[$(date)][$APPNAME] Starting the Data Connector with the following commandline:"
echo "[$(date)][$APPNAME] ${BEAST_FEEDER_COMMAND[*]}"

# Now we can start parsing data from SOURCE and pass it to DEST:
touch /run/lock/beast-feeder.up
"${BEAST_FEEDER_COMMAND[@]}" 2>&1 \
     | stdbuf -o0 sed --unbuffered '/^$/d' | stdbuf -o0 awk '{print "[" strftime("%a %b %e %T %Z %Y", systime()) "]['"$APPNAME"'] " $0}'
rm -rf /run/lock/beast-feeder.up
echo "[$(date)][$APPNAME] ---------------------------------------------------------------"
echo "[$(date)][$APPNAME] The Data Connector exited... we will restart in 10 seconds"
sleep 10
