version: "3.8"

services:

  skysquitter:
    image: ghcr.io/kx1t/docker-skysquitter
    container_name: ssq
    hostname: ssq
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - SYS_NICE
    environment:
      - WG_PRIVKEY=${SSQ_WG_PRIVKEY}
      - WG_PSK=${SSQ_WG_PSK}
      - RECV_HOST=readsb
      - MY_IP=10.9.2.xx
      - SET_TIMESTAMP=false
    volumes:
      - /opt/adsb/skysquitter:/config
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    tmpfs:
      - /run:exec,rw
      - /tmp:noexec
    depends_on:
      - readsb

# The following readsb section is provided for reference only. If you use a containerized setup,
# you should already have a corresponding section in your existing docker-compose.yml.
# If you are feeding from software on the host or another machine, replace RECV_HOST in the SkySquitter section above
# with the IP address of that machine. IT SHOULD NEVER BE SET TO 127.0.0.1 or "localhost" !
  readsb:
    image: ghcr.io/sdr-enthusiasts/docker-readsb-protobuf
    tty: true
    container_name: readsb
    hostname: readsb
    restart: always
    environment:
      - TZ=America/New_York
      - DISABLE_PERFORMANCE_GRAPHS=true
      - DISABLE_WEBAPP=true
      - READSB_NET_ENABLE=true
      - READSB_NET_ONLY=true
      - READSB_FORWARD_MLAT=true
      - READSB_NET_BEAST_OUTPUT_PORT=30005
    tmpfs:
      - /run/readsb
