#!/command/with-contenv bash
# shellcheck shell=bash disable=SC2016,SC1091

# This module makes sure that the timezone is set to UTC if SET_TIMESTAMP is enabled
# configure and start up WireGuard

APPNAME="$(hostname)/$0"

# load common functions
source /scripts/common
# preconfige s6wrap with some args:
s6wrap=(s6wrap --quiet --timestamps --prepend="${APPNAME}" --args)

if chk_enabled "${SET_TIMESTAMP}"; then
    tmzn="$(date +%z)"
    tmzn="${tmzn: -4}"
    if [[ "$tmzn" != "0000" ]]; then
        "${s6wrap[@]}" echo "FATAL: SET_TIMESTAMP is enabled but the container time is not set to UTC."
        "${s6wrap[@]}" echo "       Correct this and restart; the container is halted and will not proceed."
        sleep infinity
    fi
fi
