#!/command/with-contenv bash
# shellcheck shell=bash disable=SC2016,SC2015,SC1091

# This module makes sure that the Private Key and Preshared Key are set before we
# configure and start up WireGuard

maxtime=60
APPNAME="$(hostname)/40-save-recv_host-ip"

# load common functions
source /scripts/common
# preconfige s6wrap with some args:
s6wrap=(s6wrap --quiet --timestamps --prepend="${APPNAME}" --args)

ip_address="$(ping -c1 "${RECV_HOST}" 2>/dev/null | head -1 | awk -F '[()]' '{print $2}')"

[[ -z "$ip_address" ]] && "${s6wrap[@]}" echo "The IP address for ${RECV_HOST} cannot be resolved. We will continue to try up to ${maxtime} seconds." || true

starttime="$(date +%s)"
while [[ -z "$ip_address" ]]
do
  # wait a bit and try again -- the Beast Source container may not yet be up
  sleep 5
  ip_address="$(ping -c1 "${RECV_HOST}" 2>/dev/null | head -1 | awk -F '[()]' '{print $2}')"
  if [[ -z "$ip_address" ]] && (( "$(date +%s)" > starttime + maxtime ))
  then
    "${s6wrap[@]}" echo "The IP address for ${RECV_HOST} cannot be resolved after trying for ${maxtime} seconds. Is your Beast Source system available?"
    exit 1
  fi
done

echo "${ip_address}" > /run/recv_host_ip

"${s6wrap[@]}" echo "The IP address for ${RECV_HOST} is ${ip_address}"
