#!/command/with-contenv bash
# shellcheck shell=bash disable=SC2015,SC1091

# This module makes sure that the Private Key and Preshared Key are set before we
# configure and start up WireGuard

APPNAME="$(hostname)/50-wireguard-setkeys"

# load common functions
source /scripts/common
# preconfige s6wrap with some args:
s6wrap=(s6wrap --quiet --timestamps --prepend="${APPNAME}" --args)

# First we do a few sanity checks:

# put a wg0.conf template in place if needed:
[[ ! -f /config/wg0.conf ]] && cp /root/wg0.conf /config || true

# make it user-readable only:
chmod u=r,go= /config/wg0.conf || true

# check if the template has been replaced:
read -r teststring < /config/wg0.conf
if [[ "${teststring:0:14}" != "# wg0 template" ]]
then
  # dont use the template as it has been replaced
  "${s6wrap[@]}" echo "Using custom uploaded wg0.conf file - ignoring environment variables"
  TEMPLATE=false
else
  # Check if a bunch of variables are available:
  EMERGENCY=false
  TEMPLATE=true

  if [[ "$WG_PRIVKEY" == "" ]]
  then
    "${s6wrap[@]}" echo "Emergency!"
    "${s6wrap[@]}" echo "WG_PRIVKEY must be set. Please update your configuration and restart the container!"
    EMERGENCY=true
  fi

  if [[ "$MY_IP" == "" ]]
  then
    "${s6wrap[@]}" echo "Emergency!"
    "${s6wrap[@]}" echo "MY_IP must be set. Please update your configuration and restart the container!"
    EMERGENCY=true
  fi
fi

# Now check if wg0.conf is available and has the necessary elements:
if [[ ! -f /config/wg0.conf ]]
then
  "${s6wrap[@]}" echo "Emergency! \"wg0.conf\" cannot be found. Please update your configuration and restart the container!"
  EMERGENCY=true
fi

if ! grep "PrivateKey =" /config/wg0.conf >/dev/null 2>&1
then
  "${s6wrap[@]}" echo "Emergency! PrivateKey variable not found in \"wg0.conf\". Please update your configuration and restart the container!"
  EMERGENCY=true
fi

if ! grep "Address =" /config/wg0.conf >/dev/null 2>&1
then
  "${s6wrap[@]}" echo "Emergency! Address variable not found in \"wg0.conf\". Please update your configuration and restart the container!"
  EMERGENCY=true
fi

if [[ "$EMERGENCY" == "true" ]]
then
  # we cannot continue... let's just stop container execution right here
  "${s6wrap[@]}" echo "Container execution halted."
  sleep infinity
fi


# Now we put in the keys in their location, but only if we're using a templated solution:
if [[ "$TEMPLATE" == "true" ]]
then
  sed -i 's|\(^\s*PrivateKey\s*=\s*\).*|\1'"$WG_PRIVKEY"'|' /config/wg0.conf
  if [[ -n "$WG_PSK" ]]
  then
      sed -i 's|[\s#]*\(PresharedKey\s*=\s*\).*|\1'"$WG_PSK"'|' /config/wg0.conf
  else
      sed -i 's|\(^\s*PresharedKey\s*=.*\)|#\1|' /config/wg0.conf
  fi

  sed -i 's|\(^\s*Address\s*=\s*\).*|\1'"$MY_IP"'|' /config/wg0.conf
fi

# And done!
