#!/command/with-contenv bash
# shellcheck shell=bash disable=SC2034,SC1091

# This module makes sure that the Private Key and Preshared Key are set before we
# configure and start up WireGuard


APPNAME="$(hostname)/71-check-destination-host"

# load common functions
source /scripts/common
# preconfige s6wrap with some args:
s6wrap=(s6wrap --quiet --timestamps --prepend="${APPNAME}" --args)

starttime="$(date +%s)"
[[ -z "$FAILURE_TIMEOUT" ]] && maxwait=60 || maxwait="$FAILURE_TIMEOUT"
while ! timeout --preserve-status 10 ping -c5 "${DEST_HOST}" >/dev/null 2>&1
do
  if (( "$(date +%s)" > starttime + maxwait ))
  then
    "${s6wrap[@]}" echo "${DEST_HOST} couldn't be reached for $maxwait seconds. Terminating this container."
    exit 1
  else
    "${s6wrap[@]}" echo "${DEST_HOST} is not yet available; $(("$(date +%s)" - starttime)) of ${maxwait} seconds elapsed. Trying again in a bit."
    sleep 5
  fi
done

"${s6wrap[@]}" echo "The SkySquitter Server at ${DEST_HOST} can be pinged - we are now ready to start sending it data"
