#!/usr/bin/with-contenv bash
#shellcheck shell=bash disable=SC2153,SC2164,SC2016

# -----------------------------------------------------------------------------------
# Copyright 2022 kx1t - licensed under the terms and conditions
# of the MIT License. The terms and conditions of this license are included with the Github
# distribution of this package, and are also available here:
# https://github.com/kx1t/docker-skysquitter/

# redirect stderr to stdout so it's picked up in the docker logs
exec 2>&1
# all errors will show a line number and the command used to produce the error
SCRIPT_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd)/$(basename "$0")"
trap 'echo -e "[ERROR] $SCRIPT_PATH in line $LINENO when executing: $BASH_COMMAND"' ERR

APPNAME="$(hostname)/clockdiff-service"
echo "[$(date)][$APPNAME] Started as an s6 service"

[[ -z "$NTP_REFSERVER" ]] && NTP_REFSERVER="pool.ntp.org"
SLEEPTIME="60s"
RUNFILE="/run/clockdiff.status"


echo "$(date +%s)000,99999,99999,\"clockdiff not yet available\"" > "${RUNFILE}"

while true
do
    sleep $SLEEPTIME
    lastchecked="$(date +%s)000"
    timediff="$(clockdiff $NTP_REFSERVER 2>&1)"

    # capture a few errors
    if grep -i "command not found" <<< "${timediff}" >/dev/null 2>&1
    then
        echo "${lastchecked},99999,99999,\"clockdiff cmd not installed\"" > "${RUNFILE}"
        echo "[$(date)][$APPNAME] Stopped clockdiff-server: clockdiff not installed"
        sleep infinity
    fi
    if grep -i "nice: Operation not permitted" <<< "${timediff}" >/dev/null 2>&1
    then
        echo "${lastchecked},99999,99999,\"NICE capability not available in container\"" > "${RUNFILE}"
        echo "[$(date)][$APPNAME] Stopped clockdiff-server: NICE capability not available in container"
        sleep infinity
    fi
    if grep -i "Name or service not known" <<< "${timediff}" >/dev/null 2>&1
    then
        echo "${lastchecked},99999,99999,\"Cannot resolve NTP server ${NTP_REFSERVER}\"" > "${RUNFILE}"
        echo "[$(date)][$APPNAME] Temporary issue resolving NTP server ${NTP_REFSERVER}"
    fi
    # sometimes the service is down
    if grep -i "is down" <<< "${timediff}" >/dev/null 2>&1
    then
        echo "[$(date)][$APPNAME] Temporary issue connecting to NTP server ${NTP_REFSERVER} (reported down)"
        continue
    fi
    # last check if at least the first field is a digit string
    x="$(awk '{print $1}' <<< "${timediff}")"
    if [ -z "${x##*[!0-9]*}" ]
    then
        echo "${lastchecked},99999,99999,\"Error: ${timediff}\"" > "${RUNFILE}"
    fi

    # if we are here, then we can print the clockdiff values
    printf "%s,%s,%s,\"\"" "$(awk '{print $1}' <<< "${timediff}")" "$(awk '{print $2}' <<< "${timediff}")" "$(awk '{print $3}' <<< "${timediff}")" > "${RUNFILE}"

done
