#!/usr/bin/with-contenv bash

#mkdir -p /config
#if [[ ! -f /config/wg0.conf ]]
#then
#  if [[ -f /root/wg0.conf ]]
#  then
#    cp /root/wg0.conf /config
#  else
#    echo "Emergency -- wg0.conf not found!"
#    exit 1
#  fi
#fi
