#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC2016

# This module makes sure that the timezone is set to UTC if SET_TIMESTAMP is enabled
# configure and start up WireGuard


APPNAME="$(hostname)/$0"

SET_TIMESTAMP="${SET_TIMESTAMP,,}"
if [[ "$SET_TIMESTAMP" == "true" ]] || [[ "$SET_TIMESTAMP" == "on" ]] || [[ "$SET_TIMESTAMP" == "enabled" ]]
then
    tmzn="$(date +%z)"
    tmzn="${tmzn: -4}"
    if [[ "$tmzn" != "0000" ]]
    then
        echo "[$(date)][${APPNAME}] FATAL: SET_TIMESTAMP is enabled but the container time is not set to UTC."
        echo "[$(date)][${APPNAME}]        Correct this and restart; the container is halted and will not proceed."
        sleep infinity
    fi
fi
