#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC2016,SC2015

# This module gets a DEV version of beast-feeder.py if needed

APPNAME="$(hostname)/30-get-beastfeeder-dev"

if [[ -z "$BEASTDEV" ]]
then
  # BEASTDEV is not defined -- we're running production code and nothing is to be done
  exit 0
fi

header="${BEASTDEV:0:4}"
header="${header,,}"

if [[ "$header" != "http" ]]
then
  BEASTDEV="https://raw.githubusercontent.com/skysquitter22/beast-feeder/dev/beast-feeder.py"
fi

tmpfile="$(mktemp)"

if ! curl -sL "$BEASTDEV" > "$tmpfile"
then
  # something went wrong
  ERRORSTRING="$(curl -sLf "$BEASTDEV" -I | head -1 | tr -cd '[:print:]')"
  echo "[$(date)][$APPNAME] Error: cannot download $BEASTDEV:"
  echo "[$(date)][$APPNAME] Download attempt resulted in \"$ERRORSTRING\"."
  echo "[$(date)][$APPNAME] We will use the production beast-feeder.py instead."
  exit 0
fi

mv -f "$tmpfile" /usr/local/bin/beast-feeder.py
chmod a+x /usr/local/bin/beast-feeder.py

echo "[$(date)][$APPNAME] DEVELOPMENT USE: Replaced beast-feeder.py with the one from $BEASTDEV"
