#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC2016

# This module makes sure that the Private Key and Preshared Key are set before we
# configure and start up WireGuard


APPNAME="$(hostname)/40-save-recv_host-ip"

ip_address="$(ping -c1 ${RECV_HOST} | head -1 | awk -F '[()]' '{print $2}')"

if [[ -z "$ip_address" ]]
then
  # wait a bit and try again -- the Beast Source container may not yet be up
  sleep 10
  ip_address="$(ping -c1 ${RECV_HOST} | head -1 | awk -F '[()]' '{print $2}')"
  if [[ -z "$ip_address" ]]
  then
    echo "[$(date)][${APPNAME}] The IP address for ${RECV_HOST} cannot be resolved. Is your Beast Source system available?"
    exit 1
  fi
fi

echo ${ip_address} > /run/recv_host_ip

echo "[$(date)][${APPNAME}] The IP address for ${RECV_HOST} is ${ip_address}"
