#!/usr/bin/with-contenv bash

# This module makes sure that the Private Key and Preshared Key are set before we
# configure and start up WireGuard


APPNAME="$(hostname)/60-start-wg"
if wg-quick up /config/wg0.conf | stdbuf -o0 sed --unbuffered '/^$/d' | stdbuf -o0 awk '{print "[$APPNAME][" strftime("%Y/%m/%d %H:%M:%S", systime()) "] " $0}'
then
  echo "[$APPNAME][$(date)] WireGuard VPN brought up successfully"
else
  echo "[$APPNAME][$(date)] WireGuard VPN failed!"
  echo "[$APPNAME][$(date)] Please check the configuration and restart the container."
  echo "[$APPNAME][$(date)] Container halted."
  sleep infinity
fi
