#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# This module makes sure that the Private Key and Preshared Key are set before we
# configure and start up WireGuard


APPNAME="$(hostname)/71-check-destination-host"

starttime="$(date +%s)"
[[ -z "$FAILURE_TIMEOUT" ]] && maxwait=60 || maxwait="$FAILURE_TIMEOUT"
while ! timeout --preserve-status 10 ping -c5 "${DEST_HOST}" >/dev/null 2>&1
do
  if (( "$(date +%s)" > starttime + maxwait ))
  then
    echo "[$(date)][$APPNAME] ${DEST_HOST} couldn't be reached for $maxwait seconds. Terminating this container."
    exit 1
  else
    echo "[$(date)][$APPNAME] ${DEST_HOST} is not yet available; $(("$(date +%s)" - starttime)) of ${maxwait} seconds elapsed. Trying again in a bit."
    sleep 5
  fi
done

echo "[$(date)][$APPNAME] Your SkySquitter Server at ${DEST_HOST} can be pinged - we are now ready to start sending it data"
